# Generated by Django 4.1.3 on 2022-11-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user_id',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
    ]
