# Generated by Django 4.0.3 on 2022-11-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationApp', '0005_alter_booking_seats_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='rem_seats',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bus',
            name='seats',
            field=models.FloatField(),
        ),
    ]
