# Generated by Django 4.0.3 on 2022-11-06 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservationApp', '0006_bus_rem_seats_alter_bus_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='rem_seats',
        ),
        migrations.AddField(
            model_name='schedule',
            name='rem_seats',
            field=models.FloatField(default=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bus',
            name='seats',
            field=models.FloatField(default=0, max_length=5),
        ),
    ]
